apiVersion: v1
kind: Namespace
metadata:
  name: eks-ai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-ai
  namespace: eks-ai
  labels:
    app: eks-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-ai
  template:
    metadata:
      labels:
        app: eks-ai
    spec:
      containers:
      - name: eks-ai
        image: shakilahamed/eks-ai-simple-java-user-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /list
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 2
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: eks-ai-service
  namespace: eks-ai
spec:
  selector:
    app: eks-ai
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
