# ----------------------------------------
# Namespace
# ----------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: eks-ai
---
# ----------------------------------------
# Secret for IndiaAPI Key
# ----------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: indiaapi-secret
  namespace: eks-ai
type: Opaque
data:
  INDIAAPI_KEY: c2stbGl2ZS1zdWVBSUJPaWd2OUVMZUxMa3p2b1ZGQ0owSGxJV2pjRVJsT09sRUg0  # base64-encoded key
---
# ----------------------------------------
# Deployment
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
